# Default Configuration for Robust Vision Fail-Safes
# AI in Safety-Critical Transport Systems

# Dataset Configuration
dataset:
  name: "CIFAR-10"
  num_classes: 10
  image_size: [32, 32, 3]
  train_split: 0.8
  val_split: 0.1
  test_split: 0.1
  batch_size: 32
  shuffle_buffer: 1000

# Model Configuration
model:
  architecture: "CNN"
  input_shape: [32, 32, 3]
  num_classes: 10
  learning_rate: 0.001
  epochs: 50
  early_stopping_patience: 10
  model_save_path: "models/vehicle_classifier.h5"

# CNN Architecture
cnn:
  filters: [32, 64, 128, 256]
  kernel_sizes: [3, 3, 3, 3]
  pool_sizes: [2, 2, 2, 2]
  dropout_rate: 0.5
  dense_units: [512, 256, 128]

# Adversarial Testing Configuration
adversarial:
  noise_types: ["gaussian", "salt_pepper", "occlusion", "blur"]
  noise_intensities: [0.1, 0.2, 0.3, 0.4, 0.5]
  occlusion_sizes: [0.1, 0.2, 0.3, 0.4, 0.5]
  blur_kernels: [3, 5, 7, 9]
  fgsm_epsilon: [0.01, 0.03, 0.05, 0.1]
  pgd_epsilon: 0.3
  pgd_alpha: 0.01
  pgd_steps: 40

# Fail-Safe Configuration
failsafe:
  confidence_threshold: 0.7
  uncertainty_threshold: 0.3
  max_retries: 3
  fallback_action: "stop"  # stop, slow_down, human_intervention
  graceful_degradation: true
  logging_level: "INFO"

# SHAP Configuration
shap:
  background_samples: 100
  explanation_samples: 50
  plot_type: "bar"  # bar, waterfall, force
  save_plots: true

# Evaluation Configuration
evaluation:
  metrics: ["accuracy", "precision", "recall", "f1", "auc"]
  cross_validation_folds: 5
  random_seed: 42
  test_size: 0.2

# Logging Configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/vision_system.log"
  max_bytes: 10485760  # 10MB
  backup_count: 5

# Hardware Configuration
hardware:
  use_gpu: true
  mixed_precision: true
  num_workers: 4
  pin_memory: true

# Safety Thresholds
safety_thresholds:
  min_confidence: 0.6
  max_prediction_time: 0.1  # seconds
  max_memory_usage: 0.8  # fraction of available memory
  max_cpu_usage: 0.9  # fraction of available CPU

# Vehicle Classes
vehicle_classes:
  0: "airplane"
  1: "automobile"
  2: "bird"
  3: "cat"
  4: "deer"
  5: "dog"
  6: "frog"
  7: "horse"
  8: "ship"
  9: "truck"

# Safety-Critical Classes
safety_critical_classes:
  automobile: 1
  truck: 9
  airplane: 0
  ship: 8

# Environment Variables
environment:
  CUDA_VISIBLE_DEVICES: "0"
  TF_FORCE_GPU_ALLOW_GROWTH: "true"
  PYTHONPATH: "."

# Paths
paths:
  data_dir: "data"
  raw_data_dir: "data/raw"
  processed_data_dir: "data/processed"
  external_data_dir: "data/external"
  models_dir: "models"
  visualizations_dir: "visualizations"
  logs_dir: "logs"
